//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretSharingDotNet {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan))
                {
                    var assemblyType = typeof(ErrorMessages);
                    var assembly = assemblyType.Assembly;
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager(assemblyType.Namespace + ".Resources.ErrorMessages", assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MinimumSecurityLevelExceeded {
            get {
                return ResourceManager.GetString("MinimumSecurityLevelExceeded", resourceCulture);
            }
        }
        
        internal static string MaximumSecurityLevelExceeded {
            get {
                return ResourceManager.GetString("MaximumSecurityLevelExceeded", resourceCulture);
            }
        }
        
        internal static string MinNumberOfSharesLowerThanTwo {
            get {
                return ResourceManager.GetString("MinNumberOfSharesLowerThanTwo", resourceCulture);
            }
        }
        
        internal static string ShareIndicesNotDistinct {
            get {
                return ResourceManager.GetString("ShareIndicesNotDistinct", resourceCulture);
            }
        }
        
        internal static string MaxSharesLowerThanMinShares {
            get {
                return ResourceManager.GetString("MaxSharesLowerThanMinShares", resourceCulture);
            }
        }

        internal static string MaxSharesExceedsMersennePrime {
            get {
                return ResourceManager.GetString("MaxSharesExceedsMersennePrime", resourceCulture);
            }
        }

        internal static string MaxSharesExceedsImplementationLimit {
            get {
                return ResourceManager.GetString("MaxSharesExceedsImplementationLimit", resourceCulture);
            }
        }

        internal static string RandomRangeExceedsMaximum {
            get {
                return ResourceManager.GetString("RandomRangeExceedsMaximum", resourceCulture);
            }
        }

        internal static string ReadOnlyCollection {
            get {
                return ResourceManager.GetString("ReadOnlyCollection", resourceCulture);
            }
        }
        
        internal static string StartArrayIndexNegative {
            get {
                return ResourceManager.GetString("StartArrayIndexNegative", resourceCulture);
            }
        }
        
        internal static string DestinationArrayHasFewerElements {
            get {
                return ResourceManager.GetString("DestinationArrayHasFewerElements", resourceCulture);
            }
        }
        
        internal static string InvalidArrayTypeCast {
            get {
                return ResourceManager.GetString("InvalidArrayTypeCast", resourceCulture);
            }
        }
        
        internal static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        internal static string ValueLowerThanX {
            get {
                return ResourceManager.GetString("ValueLowerThanX", resourceCulture);
            }
        }
        
        internal static string DataTypeNotSupported {
            get {
                return ResourceManager.GetString("DataTypeNotSupported", resourceCulture);
            }
        }
        
        internal static string NoMaximumY {
            get {
                return ResourceManager.GetString("NoMaximumY", resourceCulture);
            }
        }
        
        internal static string NoValidMersennePrimeExponentAvailable {
            get {
                return ResourceManager.GetString("NoValidMersennePrimeExponentAvailable", resourceCulture);
            }
        }
        
        internal static string InverseOfZeroDoesNotExist {
            get {
                return ResourceManager.GetString("InverseOfZeroDoesNotExist", resourceCulture);
            }
        }
        
        internal static string DenominatorIsNotInvertibleModuloPrime {
            get {
                return ResourceManager.GetString("DenominatorIsNotInvertibleModuloPrime", resourceCulture);
            }
        }
        
        internal static string ShareIndexMustBePositive {
            get {
                return ResourceManager.GetString("ShareIndexMustBePositive", resourceCulture);
            }
        }
        
        internal static string ShareStringCannotBeEmpty {
            get {
                return ResourceManager.GetString("ShareStringCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ShareIndexAndValueMustBeNonEmpty {
            get {
                return ResourceManager.GetString("ShareIndexAndValueMustBeNonEmpty", resourceCulture);
            }
        }
        
        internal static string HexStringMustBeEven {
            get {
                return ResourceManager.GetString("HexStringMustBeEven", resourceCulture);
            }
        }
        
        internal static string InvalidHexCharacter {
            get {
                return ResourceManager.GetString("InvalidHexCharacter", resourceCulture);
            }
        }
        
        internal static string InvalidShareFormat {
            get {
                return ResourceManager.GetString("InvalidShareFormat", resourceCulture);
            }
        }

        internal static string LengthOutOfRangeForCapacity {
            get {
                return ResourceManager.GetString("LengthOutOfRangeForCapacity", resourceCulture);
            }
        }

        internal static string IndexOutOfRangeForLength {
            get {
                return ResourceManager.GetString("IndexOutOfRangeForLength", resourceCulture);
            }
        }

        internal static string ArgumentMustBeArrayButWasX {
            get {
                return ResourceManager.GetString("ArgumentMustBeArrayButWasX", resourceCulture);
            }
        }

        internal static string ArgumentArrayLengthMismatch {
            get {
                return ResourceManager.GetString("ArgumentArrayLengthMismatch", resourceCulture);
            }
        }

        internal static string CountedComparerRequiredForCompare {
            get {
                return ResourceManager.GetString("CountedComparerRequiredForCompare", resourceCulture);
            }
        }

        internal static string CountedComparerRequiredForHash {
            get {
                return ResourceManager.GetString("CountedComparerRequiredForHash", resourceCulture);
            }
        }

        internal static string CountExceedsBothArrayLengths {
            get {
                return ResourceManager.GetString("CountExceedsBothArrayLengths", resourceCulture);
            }
        }

        internal static string CountExceedsArrayLength {
            get {
                return ResourceManager.GetString("CountExceedsArrayLength", resourceCulture);
            }
        }

        internal static string ComparerExpectedTypeX {
            get {
                return ResourceManager.GetString("ComparerExpectedTypeX", resourceCulture);
            }
        }

        internal static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }

        internal static string NumberFormatSignWithoutDigits {
            get {
                return ResourceManager.GetString("NumberFormatSignWithoutDigits", resourceCulture);
            }
        }

        internal static string NumberFormatInvalidChar {
            get {
                return ResourceManager.GetString("NumberFormatInvalidChar", resourceCulture);
            }
        }

        internal static string DivisionByZero {
            get {
                return ResourceManager.GetString("DivisionByZero", resourceCulture);
            }
        }

        internal static string ExponentMustBeNonNegative {
            get {
                return ResourceManager.GetString("ExponentMustBeNonNegative", resourceCulture);
            }
        }

        internal static string OperandMustBeNonNegative {
            get {
                return ResourceManager.GetString("OperandMustBeNonNegative", resourceCulture);
            }
        }

        internal static string OperandMustBePositiveAndOdd {
            get {
                return ResourceManager.GetString("OperandMustBePositiveAndOdd", resourceCulture);
            }
        }

        internal static string MersenneModulusMustBeOdd {
            get {
                return ResourceManager.GetString("MersenneModulusMustBeOdd", resourceCulture);
            }
        }

        internal static string SecretNotInitialized {
            get {
                return ResourceManager.GetString("SecretNotInitialized", resourceCulture);
            }
        }

        internal static string LengthOutOfRangeForUlong {
            get {
                return ResourceManager.GetString("LengthOutOfRangeForUlong", resourceCulture);
            }
        }

        internal static string ModulusMustNotBeZero {
            get {
                return ResourceManager.GetString("ModulusMustNotBeZero", resourceCulture);
            }
        }

        internal static string ValueTooLargeForInt {
            get {
                return ResourceManager.GetString("ValueTooLargeForInt", resourceCulture);
            }
        }

        internal static string ValueTooLargeForLong {
            get {
                return ResourceManager.GetString("ValueTooLargeForLong", resourceCulture);
            }
        }

        internal static string MaxLengthMustBePositive {
            get {
                return ResourceManager.GetString("MaxLengthMustBePositive", resourceCulture);
            }
        }

        internal static string ConsoleInputRedirected {
            get {
                return ResourceManager.GetString("ConsoleInputRedirected", resourceCulture);
            }
        }

        internal static string InvalidBase64CharAtPosition {
            get {
                return ResourceManager.GetString("InvalidBase64CharAtPosition", resourceCulture);
            }
        }

        internal static string InvalidBase64Length {
            get {
                return ResourceManager.GetString("InvalidBase64Length", resourceCulture);
            }
        }

        internal static string InvalidBase64Padding {
            get {
                return ResourceManager.GetString("InvalidBase64Padding", resourceCulture);
            }
        }

        internal static string SecurityLevelNotInitialized {
            get {
                return ResourceManager.GetString("SecurityLevelNotInitialized", resourceCulture);
            }
        }

        internal static string PinnedBufferLengthMismatch {
            get {
                return ResourceManager.GetString("PinnedBufferLengthMismatch", resourceCulture);
            }
        }
    }
}
