//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretSharingDotNet {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan))
                {
                    var assemblyType = typeof(ErrorMessages);
                    var assembly = assemblyType.Assembly;
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager(assemblyType.Namespace + ".Resources.ErrorMessages", assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MinimumSecurityLevelExceeded {
            get {
                return ResourceManager.GetString("MinimumSecurityLevelExceeded", resourceCulture);
            }
        }
        
        internal static string MaximumSecurityLevelExceeded {
            get {
                return ResourceManager.GetString("MaximumSecurityLevelExceeded", resourceCulture);
            }
        }
        
        internal static string MinNumberOfSharesLowerThanTwo {
            get {
                return ResourceManager.GetString("MinNumberOfSharesLowerThanTwo", resourceCulture);
            }
        }
        
        internal static string FinitePointsNotDistinct {
            get {
                return ResourceManager.GetString("FinitePointsNotDistinct", resourceCulture);
            }
        }
        
        internal static string MaxSharesLowerThanMinShares {
            get {
                return ResourceManager.GetString("MaxSharesLowerThanMinShares", resourceCulture);
            }
        }
        
        internal static string ReadOnlyCollection {
            get {
                return ResourceManager.GetString("ReadOnlyCollection", resourceCulture);
            }
        }
        
        internal static string StartArrayIndexNegative {
            get {
                return ResourceManager.GetString("StartArrayIndexNegative", resourceCulture);
            }
        }
        
        internal static string DestinationArrayHasFewerElements {
            get {
                return ResourceManager.GetString("DestinationArrayHasFewerElements", resourceCulture);
            }
        }
        
        internal static string InvalidArrayTypeCast {
            get {
                return ResourceManager.GetString("InvalidArrayTypeCast", resourceCulture);
            }
        }
        
        internal static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        internal static string ValueLowerThanX {
            get {
                return ResourceManager.GetString("ValueLowerThanX", resourceCulture);
            }
        }
        
        internal static string DataTypeNotSupported {
            get {
                return ResourceManager.GetString("DataTypeNotSupported", resourceCulture);
            }
        }
        
        internal static string NoMaximumY {
            get {
                return ResourceManager.GetString("NoMaximumY", resourceCulture);
            }
        }
    }
}
