// ----------------------------------------------------------------------------
// <copyright file="DemoApp.cs" company="Private">
// Copyright (c) 2026 All Rights Reserved
// </copyright>
// <author>Sebastian Walther</author>
// <date>05/17/2026</date>
// ----------------------------------------------------------------------------

#region License
// ----------------------------------------------------------------------------
// Copyright 2026 Sebastian Walther
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
#endregion

namespace SecretSharingDotNet.Demo.Console;

using System;
using System.Collections.Generic;
using System.Linq;
using Cryptography;
using Cryptography.SecureArray;
using Cryptography.SecureInput;
using Math.Numerics;

/// <summary>
/// Interactive demonstration of Shamir's Secret Sharing with the
/// <see cref="SecureBigInteger"/> backend, a constant-time
/// <c>MersenneSafeGcdAlgorithm</c> inverse, and
/// <see cref="ConsolePasswordReader"/> input that never materialises the
/// secret as a <see cref="string"/>. The use cases are injected via
/// <c>Microsoft.Extensions.DependencyInjection</c>; see
/// <see cref="Program.BuildServiceProvider"/> for the wiring.
/// </summary>
internal sealed class DemoApp
{
    /// <summary>
    /// Default upper bound (in characters) for the secret entered at the console.
    /// Used by <see cref="PromptConfiguration"/> when the user accepts the default.
    /// </summary>
    private const int DefaultMaxSecretChars = 128;

    /// <summary>
    /// Default total number of shares (N) generated by the Shamir split.
    /// Used by <see cref="PromptConfiguration"/> when the user accepts the default.
    /// </summary>
    private const int DefaultTotalShares = 5;

    /// <summary>
    /// Default reconstruction threshold (K) — minimum number of shares required to
    /// recover the secret. Used by <see cref="PromptConfiguration"/> when the user
    /// accepts the default.
    /// </summary>
    private const int DefaultThreshold = 3;

    /// <summary>
    /// Use case that performs the Shamir split of a secret into N shares.
    /// Owned by the DI container (registered scoped); not disposed by this class.
    /// </summary>
    private readonly IMakeSharesUseCase<SecureBigInteger> splitter;

    /// <summary>
    /// Use case that reconstructs a secret from any K out of N shares.
    /// Owned by the DI container (registered scoped); not disposed by this class.
    /// </summary>
    private readonly IReconstructionUseCase<SecureBigInteger> reconstructor;

    /// <summary>
    /// Runtime parameters chosen by the user at startup.
    /// </summary>
    /// <param name="MaxSecretChars">Maximum number of characters accepted for the secret input.</param>
    /// <param name="TotalShares">Total number of shares (N) to generate.</param>
    /// <param name="Threshold">Number of shares (K) required for reconstruction; must satisfy <c>2 &lt;= K &lt;= N</c>.</param>
    private readonly record struct DemoConfig(int MaxSecretChars, int TotalShares, int Threshold);

    /// <summary>
    /// Initialises a new <see cref="DemoApp"/> instance with use cases supplied by the DI container.
    /// </summary>
    /// <param name="splitter">Share-creation use case for the <see cref="SecureBigInteger"/> backend.</param>
    /// <param name="reconstructor">Share-reconstruction use case for the <see cref="SecureBigInteger"/> backend.</param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="splitter"/> or <paramref name="reconstructor"/> is <see langword="null"/>.
    /// </exception>
    public DemoApp(
        IMakeSharesUseCase<SecureBigInteger> splitter,
        IReconstructionUseCase<SecureBigInteger> reconstructor)
    {
        this.splitter = splitter ?? throw new ArgumentNullException(nameof(splitter));
        this.reconstructor = reconstructor ?? throw new ArgumentNullException(nameof(reconstructor));
    }

    /// <summary>
    /// Runs the end-to-end demo: prompts for configuration and a secret, splits the
    /// secret into shares, lets the user pick a K-subset, reconstructs the secret, and
    /// reports whether the round-trip matches the original.
    /// </summary>
    /// <returns>
    /// Process exit code:
    /// <list type="bullet">
    ///   <item><description><c>0</c> — success (secret reconstructed and round-trip verified).</description></item>
    ///   <item><description><c>1</c> — recoverable error (empty input or thrown exception).</description></item>
    ///   <item><description><c>2</c> — standard input is redirected; the demo requires an interactive console.</description></item>
    /// </list>
    /// </returns>
    public int Run()
    {
        PrintBanner();

        if (Console.IsInputRedirected)
        {
            Console.Error.WriteLine("Interactive console required (ConsolePasswordReader cannot read from a pipe).");
            return 2;
        }

        try
        {
            var config = PromptConfiguration();
            Console.WriteLine();
            Console.WriteLine($"Scheme  : Shamir({config.Threshold}-of-{config.TotalShares}), max secret length {config.MaxSecretChars} chars");
            Console.WriteLine();

            using var secretChars = ReadSecretFromConsole(config.MaxSecretChars);
            if (secretChars.Length == 0)
            {
                Console.Error.WriteLine("Empty secret. Abort.");
                return 1;
            }

            using var secret = Secret<SecureBigInteger>.FromText(secretChars);
            using var shares = this.splitter.MakeShares(config.Threshold, config.TotalShares, secret);

            PrintShares(shares);

            var selectedIndices = PromptShareSelection(config.TotalShares, config.Threshold);
            using var subset = SelectShares(shares, selectedIndices);

            using var recovered = this.reconstructor.Reconstruction(subset);
            using var recoveredChars = recovered.ToCharArray();

            Console.Write("Recovered secret: ");
            Console.Out.Write(recoveredChars.PoolArray, 0, recoveredChars.Length);
            Console.WriteLine();
            Console.WriteLine($"Round-trip equals original: {secret.Equals(recovered)}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    /// <summary>
    /// Writes the startup banner — backend, GCD algorithm, input source, and DI framework —
    /// to <see cref="Console.Out"/>.
    /// </summary>
    private static void PrintBanner()
    {
        Console.WriteLine("=== SecretSharingDotNet Demo ===");
        Console.WriteLine("Backend : SecureBigInteger (pinned, zeroised on dispose)");
        Console.WriteLine("GCD     : MersenneSafeGcdAlgorithm (constant-time inverse)");
        Console.WriteLine("Input   : ConsolePasswordReader (no string materialisation)");
        Console.WriteLine("Wiring  : Microsoft.Extensions.DependencyInjection");
        Console.WriteLine();
    }

    /// <summary>
    /// Interactively prompts for the three runtime parameters
    /// (<see cref="DemoConfig.MaxSecretChars"/>, <see cref="DemoConfig.TotalShares"/>,
    /// <see cref="DemoConfig.Threshold"/>) using the corresponding <c>Default*</c>
    /// constants as fallbacks for empty input. Re-prompts until each value is valid.
    /// </summary>
    /// <returns>The configuration assembled from the user's responses.</returns>
    /// <exception cref="InvalidOperationException">Standard input is closed mid-prompt.</exception>
    private static DemoConfig PromptConfiguration()
    {
        Console.WriteLine("Configuration (press Enter to accept the default):");
        var maxChars = PromptInt("  Max secret length", DefaultMaxSecretChars, min: 1);
        var total = PromptInt("  Total shares (N)", DefaultTotalShares, min: 2);
        var threshold = PromptInt("  Threshold (K)", DefaultThreshold, min: 2, max: total);
        return new DemoConfig(maxChars, total, threshold);
    }

    /// <summary>
    /// Reads a single bounded integer from the console, re-prompting on parse failure
    /// or out-of-range input. Empty input returns <paramref name="default"/>.
    /// </summary>
    /// <param name="label">Label written before the input prompt (e.g. <c>"Total shares (N)"</c>).</param>
    /// <param name="default">Value returned when the user submits an empty line.</param>
    /// <param name="min">Inclusive lower bound for accepted input.</param>
    /// <param name="max">Optional inclusive upper bound; <see langword="null"/> means no upper bound.</param>
    /// <returns>The validated integer entered by the user, or <paramref name="default"/> on empty input.</returns>
    /// <exception cref="InvalidOperationException">Standard input is closed before a value can be read.</exception>
    private static int PromptInt(string label, int @default, int min, int? max = null)
    {
        var range = max.HasValue ? $"{min}..{max.Value}" : $">= {min}";
        while (true)
        {
            Console.Write($"{label} [{@default}] ({range}): ");
            var line = Console.ReadLine();
            if (line is null)
            {
                throw new InvalidOperationException("Standard input closed.");
            }

            var trimmed = line.Trim();
            if (trimmed.Length == 0)
            {
                return @default;
            }

            if (int.TryParse(trimmed, out var value) && value >= min && (!max.HasValue || value <= max.Value))
            {
                return value;
            }

            Console.WriteLine($"    Invalid value. Expected an integer in {range}.");
        }
    }

    /// <summary>
    /// Prompts for and reads a secret of up to <paramref name="maxSecretChars"/> characters
    /// directly into a pinned, securely cleared <see cref="PinnedPoolArray{T}"/> via
    /// <see cref="ConsolePasswordReader"/>. No <see cref="string"/> instance is created.
    /// </summary>
    /// <param name="maxSecretChars">Maximum number of characters to accept.</param>
    /// <returns>
    /// A pinned buffer holding the entered characters. The caller is responsible for disposing it.
    /// </returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="maxSecretChars"/> is not positive.</exception>
    /// <exception cref="InvalidOperationException">Standard input is redirected.</exception>
    private static PinnedPoolArray<char> ReadSecretFromConsole(int maxSecretChars)
    {
        Console.Write($"Enter secret (max {maxSecretChars} chars, input hidden): ");
        var pinned = ConsolePasswordReader.ReadPassword(maxSecretChars, echoChar: '*');
        Console.WriteLine();
        return pinned;
    }

    /// <summary>
    /// Writes the generated shares to <see cref="Console.Out"/> in the public
    /// <c>"INDEX-VALUE"</c> hex serialisation. The index in square brackets is the
    /// one-based position in <paramref name="shares"/>, matching the indices accepted
    /// by <see cref="PromptShareSelection"/>.
    /// </summary>
    /// <param name="shares">The share collection to print.</param>
    private static void PrintShares(Shares<SecureBigInteger> shares)
    {
        Console.WriteLine();
        Console.WriteLine($"Generated {shares.Count} shares (keep each one confidential):");
        for (int i = 0; i < shares.Count; i++)
        {
            // Share.ToString() emits the public "INDEX-VALUE" hex serialisation; safe to print.
            Console.WriteLine($"  [{i + 1}] {shares[i]}");
        }

        Console.WriteLine();
    }

    /// <summary>
    /// Prompts for exactly <paramref name="threshold"/> distinct one-based share indices
    /// in the range <c>1..total</c>, re-prompting until the input is well-formed.
    /// </summary>
    /// <param name="total">Total number of available shares (upper bound for accepted indices).</param>
    /// <param name="threshold">Required number of distinct indices to collect.</param>
    /// <returns>The list of selected indices in the order entered by the user.</returns>
    /// <exception cref="InvalidOperationException">Standard input is closed mid-prompt.</exception>
    private static IReadOnlyList<int> PromptShareSelection(int total, int threshold)
    {
        while (true)
        {
            Console.Write($"Select {threshold} shares to reconstruct (comma-separated, 1..{total}): ");
            var line = Console.ReadLine();
            if (line is null)
            {
                throw new InvalidOperationException("Standard input closed.");
            }

            var parsed = ParseIndices(line, total);
            if (parsed.Count == threshold)
            {
                return parsed;
            }

            Console.WriteLine($"  Need exactly {threshold} distinct indices in 1..{total}. Try again.");
        }
    }

    /// <summary>
    /// Parses a comma-separated list of one-based share indices. Duplicates are
    /// silently dropped, blank entries are ignored, and any out-of-range or
    /// non-numeric entry collapses the whole result to an empty list (signalling
    /// "invalid" to <see cref="PromptShareSelection"/>).
    /// </summary>
    /// <param name="line">Raw input line, e.g. <c>"1, 3, 4"</c>.</param>
    /// <param name="total">Inclusive upper bound for accepted indices.</param>
    /// <returns>
    /// The parsed unique indices in input order, or an empty list when any entry is invalid.
    /// </returns>
    private static List<int> ParseIndices(string line, int total)
    {
        var result = new List<int>();
        var seen = new HashSet<int>();
        foreach (var part in line.Split(','))
        {
            var trimmed = part.Trim();
            if (trimmed.Length == 0)
            {
                continue;
            }

            if (!int.TryParse(trimmed, out var idx) || idx < 1 || idx > total)
            {
                return [];
            }

            if (seen.Add(idx))
            {
                result.Add(idx);
            }
        }

        return result;
    }

    /// <summary>
    /// Returns a <see cref="Shares{TNumber}"/> wrapper around the subset of
    /// <paramref name="all"/> picked by the supplied one-based positions. Because
    /// the original and the subset wrapper share the same <c>Share</c> instances,
    /// disposing either is safe — <c>Share.Dispose</c> is idempotent.
    /// </summary>
    /// <param name="all">The full share collection (sorted by index).</param>
    /// <param name="oneBasedIndices">Positions in <paramref name="all"/> to include, one-based.</param>
    /// <returns>A new <see cref="Shares{TNumber}"/> wrapper containing the picked shares.</returns>
    private static Shares<SecureBigInteger> SelectShares(
        Shares<SecureBigInteger> all,
        IReadOnlyList<int> oneBasedIndices)
    {
        // The implicit Share[] -> Shares operator gives us back a fresh collection wrapper
        // that still references the original shares.
        var picked = oneBasedIndices.Select(i => all[i - 1]).ToArray();
        return picked;
    }
}